export const REQUEST_DIRECT_INBOX_SUCCESS = 'REQUEST_DIRECT_INBOX_SUCCESS';
export const REQUEST_DIRECT_INBOX = 'REQUEST_DIRECT_INBOX';

export const REQUEST_DIRECT_NEXT_PAGE = 'REQUEST_DIRECT_NEXT_PAGE';
export const REQUEST_DIRECT_NEXT_PAGE_SUCCESS = 'REQUEST_DIRECT_NEXT_PAGE_SUCCESS';