export const REQUEST_DIRECT_INBOX_SUCCESS = 'REQUEST_DIRECT_INBOX_SUCCESS';
export const REQUEST_DIRECT_INBOX = 'REQUEST_DIRECT_INBOX';

export const REQUEST_DIRECT_NEXT_PAGE = 'REQUEST_DIRECT_NEXT_PAGE';
export const REQUEST_DIRECT_NEXT_PAGE_SUCCESS = 'REQUEST_DIRECT_NEXT_PAGE_SUCCESS';

export const DIRECT_SEND_MESSAGE = 'DIRECT_SEND_MESSAGE';
export const DIRECT_SEND_MESSAGE_SUCCESS = 'DIRECT_SEND_MESSAGE_SUCCESS';

export const DIRECT_RECEIVE_MESSAGE = 'DIRECT_RECEIVE_MESSAGE';